version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/recipes/images

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  nginx:
    image: nginx:1.19.3
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - media:/app/media/recipes/images
      - static:/static/

      - ./nginx.conf:/etc/nginx/conf.d/default.conf
