# Generated by Django 3.2.3 on 2023-08-01 10:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230730_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(help_text='Введите меру измерения ингредиента', max_length=10, verbose_name='Мера объёма ингредиента'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Введите цвет тега в HEX-кодировке', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет тега'),
        ),
    ]
