# Generated by Django 3.2.3 on 2023-08-02 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230801_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(help_text='Укажите количество ингредиента', validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиентов должно быть больше нуля!')], verbose_name='Количество ингредиентов'),
        ),
    ]
