# Generated by Django 3.2.3 on 2023-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={'ordering': ('id',), 'verbose_name': 'Подписки'},
        ),
    ]
